name: Build and Test
run-name: Build and Test
on: [push]
jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: "yarn --prefer-offline"
      - run: "yarn build"
      - run: "yarn lint"
      - run: "yarn test"
